Fixed doxygen index page
adafruit/Adafruit_LIS2MDL pull request #5
Opened 2020-05-25 18:42 UTC by dherrada

2020-05-25 18:57 UTC, ladyada approved these changes

2020-05-25 19:02 UTC, ladyada commented
@siddacious looks like needs some doxy

2020-05-30 04:03 UTC, siddacious requested changes

2020-05-30 04:03 UTC, siddacious commented on Adafruit_LIS2MDL.h
> + * @file Adafruit_LIS2MDL.h
Just add the `@file`, don't remove the attribution etc.

2020-06-01 20:28 UTC, siddacious approved these changes

2020-06-01 20:29 UTC, merged